# Generated by Django 6.1.1 on 2026-09-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='image',
            field=models.ImageField(blank=True, upload_to='cafes/'),
        ),
    ]
