# Generated by Django 6.1.1 on 2026-09-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0004_cafesuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='business_hours',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
