# Generated by Django 6.1.1 on 2026-09-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0008_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, help_text='가로형 이미지(권장 1600×1000)를 사용하세요. 비어 있으면 기존 일러스트가 표시됩니다.', upload_to='hero/', verbose_name='Hero 대표 이미지')),
                ('position', models.CharField(choices=[('center', '가운데'), ('left', '왼쪽'), ('right', '오른쪽')], default='center', max_length=6, verbose_name='이미지 위치')),
            ],
            options={
                'verbose_name': '메인 Hero 배너',
                'verbose_name_plural': '메인 Hero 배너',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='single_hero_banner')],
            },
        ),
    ]
