# Generated by Django 6.1.1 on 2026-09-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0009_herobanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='blog_url',
            field=models.URLField(blank=True, verbose_name='블로그 후기 URL'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='is_matchayojung_pick',
            field=models.BooleanField(default=False, verbose_name='말차요정 PICK'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='matchayojung_comment',
            field=models.TextField(blank=True, max_length=200, verbose_name='말차요정 한줄평'),
        ),
    ]
