# Generated by Django 6.1.1 on 2026-09-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0010_cafe_blog_url_cafe_is_matchayojung_pick_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='city',
            field=models.CharField(choices=[('seoul', '서울'), ('tokyo', '도쿄'), ('osaka', '오사카'), ('new-york', '뉴욕'), ('san-francisco', '샌프란시스코')], default='seoul', max_length=30, verbose_name='도시'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='country',
            field=models.CharField(choices=[('KR', '한국'), ('JP', '일본'), ('US', '미국')], default='KR', max_length=2, verbose_name='국가'),
        ),
    ]
