# Generated by Django 6.1.1 on 2026-09-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0012_classify_existing_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='city',
            field=models.CharField(choices=[('seoul', '서울'), ('tokyo', '도쿄'), ('osaka', '오사카'), ('new-york', '뉴욕'), ('san-francisco', '샌프란시스코'), ('jeju', '제주'), ('boston', '보스턴')], default='seoul', max_length=30, verbose_name='도시'),
        ),
    ]
