# Generated by Django 6.1.1 on 2026-10-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0013_alter_cafe_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafesuggestion',
            name='city',
            field=models.CharField(choices=[('seoul', '서울'), ('tokyo', '도쿄'), ('osaka', '오사카'), ('new-york', '뉴욕'), ('san-francisco', '샌프란시스코'), ('jeju', '제주'), ('boston', '보스턴')], default='seoul', max_length=30, verbose_name='도시'),
        ),
        migrations.AddField(
            model_name='cafesuggestion',
            name='country',
            field=models.CharField(choices=[('KR', '한국'), ('JP', '일본'), ('US', '미국')], default='KR', max_length=2, verbose_name='국가'),
        ),
    ]
